// Generated by CoffeeScript 1.4.0
var $, initGame;

$ = Zepto;

$(function() {
  return initGame();
});

initGame = function() {
  var COLOURS, INITIAL_CHARACTER_COLUMN, INITIAL_COLUMNS, INITIAL_ROWS, MAX_ROWS, NEW_ROW_INTERVAL, addRow, addRowOrRestartGame, alive, balls, board, characterBalls, characterColumn, column, columnIndex, columns, countRows, moveCharacterToColumn, pullBall, pushBall, rowIndex, rows, _i, _j, _ref, _ref1;
  $('#sausis .board').remove();
  board = $('<div/>');
  board.addClass('board');
  $('#sausis').append(board);
  alive = true;
  INITIAL_COLUMNS = 5;
  columns = INITIAL_COLUMNS;
  balls = [];
  for (columnIndex = _i = 0, _ref = INITIAL_COLUMNS - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; columnIndex = 0 <= _ref ? ++_i : --_i) {
    column = $('<div />');
    column.addClass('column');
    column.data('x', columnIndex);
    board.append(column);
    balls.push([]);
  }
  INITIAL_ROWS = 5;
  MAX_ROWS = 8;
  rows = 0;
  COLOURS = ['red', 'blue', 'green'];
  countRows = function() {
    var maxBalls, _j, _len;
    maxBalls = 0;
    for (_j = 0, _len = balls.length; _j < _len; _j++) {
      column = balls[_j];
      if (column.length > maxBalls) {
        maxBalls = column.length;
      }
    }
    return maxBalls;
  };
  addRow = function() {
    var ball, colour, rowIndex, _j, _ref1, _results;
    rowIndex = rows++;
    if (countRows() >= MAX_ROWS) {
      alive = false;
      return;
    }
    _results = [];
    for (columnIndex = _j = 0, _ref1 = columns - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; columnIndex = 0 <= _ref1 ? ++_j : --_j) {
      column = $(".column[data-x='" + columnIndex + "']");
      colour = COLOURS[Math.floor(Math.random() * COLOURS.length)];
      ball = $('<div />');
      ball.addClass('ball');
      ball.addClass(colour);
      ball.data('x', columnIndex);
      ball.data('y', rowIndex);
      balls[columnIndex].push(ball);
      _results.push(column.prepend(ball));
    }
    return _results;
  };
  for (rowIndex = _j = 0, _ref1 = INITIAL_ROWS - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; rowIndex = 0 <= _ref1 ? ++_j : --_j) {
    addRow();
  }
  NEW_ROW_INTERVAL = 5000;
  addRowOrRestartGame = function() {
    if (alive) {
      addRow();
      return setTimeout(addRowOrRestartGame, NEW_ROW_INTERVAL);
    } else {
      return initGame();
    }
  };
  setTimeout(addRowOrRestartGame, NEW_ROW_INTERVAL);
  INITIAL_CHARACTER_COLUMN = 2;
  characterColumn = null;
  moveCharacterToColumn = function(columnIndex) {
    var character;
    if (columnIndex !== characterColumn) {
      characterColumn = columnIndex;
      $(".character").remove();
      character = $('<div/>');
      character.addClass('character');
      column = $(".column[data-x='" + characterColumn + "']");
      return column.append(character);
    }
  };
  moveCharacterToColumn(INITIAL_CHARACTER_COLUMN);
  characterBalls = [];
  pullBall = function(columnIndex) {
    var ball;
    ball = balls[columnIndex].shift();
    if (ball) {
      ball.remove();
      return characterBalls.push(ball);
    }
  };
  pushBall = function(columnIndex) {
    var ball;
    if (countRows() >= MAX_ROWS) {
      return false;
    }
    ball = characterBalls.pop();
    if (ball) {
      balls[columnIndex].unshift(ball);
      return $(".column[data-x='" + columnIndex + "']").append(ball);
    }
  };
  window.onkeydown = function(e) {
    if (e.keyCode === 40 || e.keyCode === 38) {
      return false;
    }
  };
  return window.onkeyup = function(e) {
    if (alive) {
      e = e.keyCode;
      switch (e) {
        case 37:
          if (characterColumn > 0) {
            return moveCharacterToColumn(characterColumn - 1);
          }
          break;
        case 39:
          if (characterColumn < INITIAL_COLUMNS - 1) {
            return moveCharacterToColumn(characterColumn + 1);
          }
          break;
        case 40:
          return pullBall(characterColumn);
        case 38:
          pushBall(characterColumn);
          return false;
      }
    }
  };
};
