// Generated by CoffeeScript 1.4.0
var $, initGame;

$ = Zepto;

$(function() {
  return initGame();
});

initGame = function() {
  var COLOURS, INITIAL_COLUMNS, INITIAL_ROWS, MAX_ROWS, NEW_ROW_INTERVAL, addRow, addRowOrRestartGame, alive, board, column, columnIndex, columns, rowIndex, rows, _i, _j, _ref, _ref1;
  $('#sausis .board').remove();
  board = $('<div/>');
  board.addClass('board');
  $('#sausis').append(board);
  alive = true;
  INITIAL_COLUMNS = 5;
  columns = INITIAL_COLUMNS;
  for (columnIndex = _i = 0, _ref = INITIAL_COLUMNS - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; columnIndex = 0 <= _ref ? ++_i : --_i) {
    column = $('<div />');
    column.addClass('column');
    column.data('x', columnIndex);
    board.append(column);
  }
  INITIAL_ROWS = 5;
  MAX_ROWS = 8;
  rows = 0;
  COLOURS = ['red', 'blue', 'green'];
  addRow = function() {
    var ball, colour, rowIndex, _j, _results;
    rowIndex = rows++;
    if (rowIndex === MAX_ROWS) {
      alive = false;
      return;
    }
    _results = [];
    for (columnIndex = _j = 0; 0 <= columns ? _j <= columns : _j >= columns; columnIndex = 0 <= columns ? ++_j : --_j) {
      column = $(".column[data-x='" + columnIndex + "']");
      colour = COLOURS[Math.floor(Math.random() * COLOURS.length)];
      ball = $('<div />');
      ball.addClass('ball');
      ball.addClass(colour);
      ball.data('x', columnIndex);
      ball.data('y', rowIndex);
      _results.push(column.prepend(ball));
    }
    return _results;
  };
  for (rowIndex = _j = 0, _ref1 = INITIAL_ROWS - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; rowIndex = 0 <= _ref1 ? ++_j : --_j) {
    addRow();
  }
  NEW_ROW_INTERVAL = 2500;
  addRowOrRestartGame = function() {
    if (alive) {
      addRow();
      return setTimeout(addRowOrRestartGame, NEW_ROW_INTERVAL);
    } else {
      return initGame();
    }
  };
  return setTimeout(addRowOrRestartGame, NEW_ROW_INTERVAL);
};
